language: cpp

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - ninja-build

install:
  # GCC 4.9
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9" GN_ARGS="gcc_cc=\"gcc-4.9\" gcc_cxx=\"g++-4.9\" is_clang=false"; fi

script:
  - git submodule update --init --recursive
  - tools/gn/bootstrap/bootstrap.py --no-clean --no-rebuild --jobs 10
  - out_bootstrap/gn gen out/Release --args="is_debug=false $GN_ARGS"
  - ninja -C out/Release -j10 gn gn_unittests
  - out/Release/gn_unittests
